apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: db-volume
        hostPath:
          path: /data/db
      containers:
      - name: mongodb
        image: dshetty1702/mongodb:latest
        ports:
        - containerPort: 27017
        volumeMounts: 
        - name: db-volume
          mountPath: /data/db